config/routes.rb
Rails.application.routes.draw do
  resources :labels
  root 'sessions#new'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update]
  namespace :admin do
    resources :users
  end
  resources :tasks

end

app/models/task.rb
class Task < ApplicationRecord
    validates :title, presence: true
    validates :content, presence: true
    belongs_to :user, optional: true

    scope :search_title, -> (title) { where("title LIKE ?", "%#{ title }%") }
    scope :search_status, -> (status) { where(status: status) }
    scope :search_labels, -> (task_id) { where(id: [task_id]) }

    enum priority:{
        高: 0, #高い
        中: 1, #普通
        下: 2, #低い
      }

    has_many :task_labels, dependent: :destroy, foreign_key: 'task_id'
    has_many :labels, through: :task_labels, source: :label
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user
  before_action :ensure_correct_user, {only: [ :edit, :update]}

  PER = 10

  def index
    if params[:sort_expired] 
      @tasks = current_user.tasks.order(end_date: :asc).page(params[:page]).per(PER)
    elsif params[:sort_priority] 
      @tasks = current_user.tasks.order(priority: :asc).page(params[:page]).per(PER)
    else
      @tasks = current_user.tasks.order(created_at: :desc).page(params[:page]).per(PER)
    end

    if params[:search].present?
      if params[:title].present? && params[:status].present? && params[:label_id].present?
        @tasks = current_user.tasks.search_title(params[:title]).search_status(params[:status]).page(params[:page]).per(PER)
      elsif params[:title].present?
        @tasks = current_user.tasks.search_title(params[:title]).page(params[:page]).per(PER)
      elsif params[:status].present?
        @tasks = current_user.tasks.search_status(params[:status]).page(params[:page]).per(PER)
      elsif params[:label_ids].present?
        @label_id = params[:label_ids]
        @task_ids = TaskLabel.where(label_id: @label_id).pluck(:task_id)
        @tasks = current_user.tasks.search_labels(@task_ids).page(params[:page]).per(PER)
      end
    end

  end  

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      redirect_to task_path(@task.id), notice: "タスクを作成しました"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: "編集しました！"
    else
      render :edit
    end
  end

  def show
    @task = Task.find(params[:id])
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, notice:"削除しました！"
  end

  private
  def task_params
    params.require(:task).permit(:title, :content, :end_date, :status, :priority, { label_ids: [] })
  end
  
  def set_task
    @task = Task.find(params[:id])
  end

  def ensure_correct_user
    if current_user.id != @task.user.id
      flash[:notice] = "権限がありません"
      redirect_to tasks_path
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<div class="border col-7">
  <div class="row">
    <div class="col-md">
<%= form_with(model: @task, local: true) do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= @task.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container">
    <div class="title">
      <%= form.label :title %>
      <%= form.text_field :title , class: 'form-control'%>
    </div>
    <div class="content">
      <%= form.label :content %>
      <%= form.text_area :content , class: 'form-control'%>
    </div>
    <div class="field">
      <%= form.label :end_date %>
      <%= form.date_field :end_date , class: 'form-control'%>
    </div>
    <div class="field">
      <%= form.label :status %>
      <%= form.select(:status, options_for_select([["未着手","未着手"],["着手中","着手中"],["完了","完了"]]), {}, {class: "form-control"})%>
    </div>
    <div class="field">
      <%= form.label :priority %>
      <%= form.select :priority, Task.priorities.keys.to_a, include_blank: true , class: "form-control"%>
    </div>
    <div class="field">
      <div class="labels">
      <%= form.label :lebel %>   
      <%= form.collection_check_boxes(:label_ids, Label.all, :id, :title) %>
      </div>
    </div>
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'タスク一覧画面に戻る', tasks_path ,class: "btn btn-info"%>
</div>
<body>

app/views/tasks/_not_logged_in.html.erb
<p>タスクの管理ができるアプリです。まずはログインをしてください。</p>
<%= link_to "ログイン", sessions_path%>

app/views/tasks/edit.html.erb
<h1>タスク編集</h1>

<%= render 'form' %>

app/views/tasks/index.html.erb
<br>
<h2><%= current_user.name %>のタスク一覧</h2>
<br>

<%= form_with url: tasks_path, method: :get, local: true do |form| %>
  <%= form.text_field :title ,placeholder:"タイトル検索"%>
  <%= form.select :status, [["未着手", "未着手"],["着手中","着手中"],["完了","完了"]], prompt: "ステータス選択"%>
  <%= form.hidden_field :search, value: 'true' %>
  <%= form.label :lebel %>   
  <%= form.collection_check_boxes(:label_ids, Label.all, :id, :title) %>
  <%= form.submit '検索', name: nil %>
<% end %>
<br>
<table class="table table-bordered">
<thead>
  <tr class="active">
    <th>ラベル</th>
    <th>タイトル</th>
    <th>内容</th>
    <th>作成日</th>
    <th>終了期限</th>
    <th>ステータス</th>
    <th>優先順位</th>
    <th>投稿者</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  
</thead>
<tbody>
<% @tasks.each do |task| %>
  <tr>
    <td><% task.task_labels.each do |task_label| %>
        <%= task_label.label.title %><br>
    <% end %></td>
    <td><%= task.title %></td>
    <td><%= task.content %></td>
    <td><%= task.created_at %></td>
    <td><%= task.end_date %></td>
    <td><%= task.status %></td>
    <td><%= task.priority %></td>
    <td><%= task.user.name %></td>
    <td><%= link_to '詳細', task_path(task.id) %></td>
    <td><%= link_to '編集', edit_task_path(task.id), data: { confirm: '本当に編集していいですか？' } %></td>
    <td><%= link_to '削除', task_path(task.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
  </tr>
<% end %>
</tbody>
</table>
<%= paginate @tasks %>
<br>
<%= link_to 'タスク作成', new_task_path, class:"btn btn-primary"%>
<%= link_to "終了期限でソートする", tasks_path(sort_expired: :true), class: "btn btn-warning"%> 
<%= link_to "優先順位でソートする", tasks_path(sort_priority: :true), class: "btn btn-warning"%>
<%= link_to '一覧画面へ', tasks_path ,class: "btn btn-info"%>

app/views/tasks/new.html.erb
<br>
<h2>新規登録</h2>
<br>
 

<%= render 'form' %>

app/views/tasks/show.html.erb
<br>
<h2>詳細画面</h2>
<br>
<table class="table table-bordered">
<thead>
  <tr class="active">
    <th>ラベル</th>
    <th>タイトル</th>
    <th>内容</th>
    <th>作成日</th>
    <th>終了期限</th>
    <th>ステータス</th>
    <th>優先順位</th>
    <th>投稿者</th>
  </tr>
</thead>
 <tbody>
  <tr>
    <td><% @task.task_labels.each do |task_label| %>
    <%= task_label.label.title %><br>
    <% end %></td>
    <td><%= @task.title %></td>
    <td><%= @task.content %></td>
    <td><%= @task.created_at %></td>
    <td><%= @task.end_date %></td>
    <td><%= @task.status %></td>
    <td><%= @task.priority %></td>
    <td><%= @task.user.name %></td>
  </tr>
</tbody>
</table>
<%= link_to 'タスク一覧画面に戻る', tasks_path ,class: "btn btn-info"%>