config/routes.rb
Rails.application.routes.draw do
  resources :labels
  root 'sessions#new'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update]
  namespace :admin do
    resources :users
  end
  resources :tasks

end

app/models/task.rb
class Task < ApplicationRecord
    validates :title, presence: true
    validates :content, presence: true
    belongs_to :user, optional: true

    scope :search_title, -> (title) { where("title LIKE ?", "%#{ title }%") }
    scope :search_status, -> (status) { where(status: status) }
    scope :search_labels, -> (task_id) { where(id: [task_id]) }

    enum priority:{
        高: 0, #高い
        中: 1, #普通
        下: 2, #低い
      }

    has_many :task_labels, dependent: :destroy, foreign_key: 'task_id'
    has_many :labels, through: :task_labels, source: :label
end

app/models/user.rb
class User < ApplicationRecord
    before_destroy :admin_exist_check
    before_update :admin_update_exist
    validates :name,  presence: true, length: { maximum: 30 }
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
    before_validation { email.downcase! }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    has_many :tasks, dependent: :destroy

    def admin_exist_check
      if User.where(admin: true).count <= 1 && self.admin == true 
        throw(:abort)
      end
    end

    def admin_update_exist
      if User.where(admin: true).count == 1 && self.admin == false
        throw(:abort)
      end
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    before_action :admin_user
    before_action :set_user, only: [:show, :edit, :destroy]

    PER = 10

    def new
      @user = User.new
    end
    def create
      @user = User.new(user_params)
      if @user.save
        redirect_to admin_user_path(@user.id)
      else
        render :new
      end
    end

    def show
      @user = User.find(params[:id])
        if params[:sort_expired] 
          @tasks = @user.tasks.order(end_date: :asc).page(params[:page]).per(PER)
        elsif params[:sort_priority] 
          @tasks = @user.tasks.order(priority: :asc).page(params[:page]).per(PER)
        else
          @tasks = @user.tasks.order(created_at: :desc).page(params[:page]).per(PER)
        end
        if params[:search].present?
          if params[:title].present? && params[:status].present? && params[:label_id].present?
            @tasks = @user.tasks.search_title(params[:title]).search_status(params[:status]).page(params[:page]).per(PER)
          elsif params[:title].present?
            @tasks = @user.tasks.search_title(params[:title]).page(params[:page]).per(PER)
          elsif params[:status].present?
            @tasks = @user.tasks.search_status(params[:status]).page(params[:page]).per(PER)
          elsif params[:label_ids].present?
            @label_id = params[:label_ids]
            @task_ids = TaskLabel.where(label_id: @label_id).pluck(:task_id)
            @tasks = @user.tasks.search_labels(@task_ids).page(params[:page]).per(PER)
          end
        end
    end

    def index
      @users = User.all.order("created_at ASC")
    end
  
    def edit
      @user = User.find(params[:id])
    end
    
  
    def update
      @user = User.find(params[:id])
      if @user.update(user_params)
          redirect_to admin_users_path, notice: "ユーザー情報を修正しました"
      else
          render :edit
      end
    end
  
    def destroy
      @user.destroy
      redirect_to admin_users_path, notice:"ユーザー情報を削除しました！"
    end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation,:image_name,:admin)
    end 

    def set_user
      @user = User.find(params[:id])
    end 

    def admin_user
      if current_user.admin?
          flash[:notice] = "あなたは管理者です"
      else
      redirect_to(tasks_path) 
      flash[:notice] = "あなたは管理者ではありません"
      end
    end 

  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user, {only: [:index,  :edit, :update]}
    before_action :user_logged_in, {only: [:new]}
    before_action :ensure_correct_user, {only: [:show, :edit, :update]}

    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
            log_in @user
            redirect_to user_path(@user.id)
        else
            render :new
        end
    end

    def show
        @user = User.find(params[:id])
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            redirect_to user_path, notice: "ユーザー情報を修正しました"
        else
            render :edit
        end
    end

    private
    def user_params
        params.require(:user).permit(:name, :email, :password,
                                     :password_confirmation)
    end

    def ensure_correct_user
        if current_user.id != params[:id].to_i
          flash[:notice] = "権限がありません"
          redirect_to tasks_path
        end
    end
    
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<h1>edit</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: [:admin,@user], local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.label :admin %>
  <%= f.check_box :admin %>
  <%= f.submit "edit account" %>
<% end %>

app/views/admin/users/index.html.erb
<h1>管理画面：ユーザー一覧</h1>
<p><%= link_to "新規ユーザー作成", new_admin_user_path, class: "btn btn-warning" %></p>
<table class="table table-bordered">
  <thead>
    <tr class="active">
      <th>ID</th>
      <th>名前</th>
      <th>管理者</th>
      <th>タスク数</th>
      <th>編集</th>
      <th>削除</th>
    </tr> 
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= link_to user.name , admin_user_path(user.id)%></td>
      <td><%= user.admin? ? '管理ユーザー' : '一般ユーザー' %></td>
      <td><%= user.tasks.size %></td>
      <% if current_user.admin? %>
        <td><%= link_to "edit", edit_admin_user_path(user.id), method: :get, data: { confirm: "編集していいですか?" } , class: "btn btn-warning"%></td>
        <td><%= link_to "delete", admin_user_path(user.id), method: :delete, data: { confirm: "削除していいですか?" } , class: "btn btn-warning"%></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/users/new.html.erb
<h1>Sign up</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: [:admin,@user], local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.label :admin %>
  <%= f.check_box :admin %>
  <%= f.submit "Create account" %>
<% end %>

app/views/admin/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<p>メールアドレス: <%= @user.email %></p>
<p><%= @user.admin? ? '管理ユーザー' : '一般ユーザー' %></p>

<br>
<h2>タスク一覧</h2>
<br>
<%= form_with url: admin_user_path, method: :get, local: true do |form| %>
  <%= form.text_field :title ,placeholder:"タイトル検索"%>
  <%= form.select :status, [["未着手", "未着手"],["着手中","着手中"],["完了","完了"]], prompt: "ステータス選択"%>
  <%= form.hidden_field :search, value: 'true' %>
  <%= form.label :lebel %>   
  <%= form.collection_check_boxes(:label_ids, Label.all, :id, :title) %>
  <%= form.submit '検索', name: nil %>
<% end %>
<br>
<table class="table table-bordered">
<thead>
  <tr class="active">
    <th>ラベル</th>
    <th>タイトル</th>
    <th>内容</th>
    <th>作成日</th>
    <th>終了期限</th>
    <th>ステータス</th>
    <th>優先順位</th>
    <th>投稿者</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  
</thead>
<tbody>
<% @tasks.each do |task| %>
  <tr>
    <td><% task.task_labels.each do |task_label| %>
        <%= task_label.label.title %><br>
    <% end %></td>
    <td><%= task.title %></td>
    <td><%= task.content %></td>
    <td><%= task.created_at %></td>
    <td><%= task.end_date %></td>
    <td><%= task.status %></td>
    <td><%= task.priority %></td>
    <td><%= task.user.name %></td>
    <td><%= link_to '詳細', task_path(task.id) %></td>
    <td><%= link_to '編集', edit_task_path(task.id), data: { confirm: '本当に編集していいですか？' } %></td>
    <td><%= link_to '削除', task_path(task.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
  </tr>
<% end %>
</tbody>
</table>
<%= paginate @tasks %>
<br>
<%= link_to 'タスク作成', new_task_path, class:"btn btn-primary"%>
<%= link_to "終了期限でソートする", admin_user_path(sort_expired: :true), class: "btn btn-warning"%> 
<%= link_to "優先順位でソートする", admin_user_path(sort_priority: :true), class: "btn btn-warning"%>

<% if current_user.admin? %>
	<%= link_to "管理者画面へ", admin_users_path,class: "btn btn-info"%>
<% end %>